"""GridWorld OTIB-style data generation.

The implementation keeps the domain deliberately small and auditable: a state is
one object on a 10x10 grid, and a hidden program is a sequence of primitive
moves. Each example contains a support transition and a query transition
generated by the same program.
"""

from __future__ import annotations

from dataclasses import dataclass
import random
from typing import Iterable, Iterator, Literal, Sequence

BoundaryMode = Literal["wrap", "clamp"]

ACTIONS: tuple[str, ...] = ("up", "down", "left", "right")
ACTION_TO_DELTA: dict[str, tuple[int, int]] = {
    "up": (-1, 0),
    "down": (1, 0),
    "left": (0, -1),
    "right": (0, 1),
}


@dataclass(frozen=True)
class GridState:
    row: int
    col: int

    def to_index(self, size: int = 10) -> int:
        return self.row * size + self.col

    @classmethod
    def from_index(cls, index: int, size: int = 10) -> "GridState":
        if index < 0 or index >= size * size:
            raise ValueError(f"state index {index} is outside a {size}x{size} grid")
        return cls(row=index // size, col=index % size)


@dataclass(frozen=True)
class GridExample:
    support_x: int
    support_y: int
    query_x: int
    query_y: int
    program: tuple[int, ...]


def apply_action(
    state: GridState,
    action: int | str,
    *,
    size: int = 10,
    boundary: BoundaryMode = "wrap",
) -> GridState:
    """Apply one primitive action to a state."""

    name = ACTIONS[action] if isinstance(action, int) else action
    if name not in ACTION_TO_DELTA:
        raise ValueError(f"unknown action: {action}")

    d_row, d_col = ACTION_TO_DELTA[name]
    row = state.row + d_row
    col = state.col + d_col

    if boundary == "wrap":
        row %= size
        col %= size
    elif boundary == "clamp":
        row = min(max(row, 0), size - 1)
        col = min(max(col, 0), size - 1)
    else:
        raise ValueError(f"unknown boundary mode: {boundary}")

    return GridState(row=row, col=col)


def apply_program(
    state: GridState,
    program: Sequence[int],
    *,
    size: int = 10,
    boundary: BoundaryMode = "wrap",
) -> GridState:
    """Apply a sequence of primitive actions."""

    current = state
    for action in program:
        current = apply_action(current, action, size=size, boundary=boundary)
    return current


def enumerate_programs(
    *,
    min_len: int = 1,
    max_len: int = 3,
    num_actions: int = len(ACTIONS),
) -> list[tuple[int, ...]]:
    """Enumerate all action programs in lexicographic order."""

    if min_len < 1 or max_len < min_len:
        raise ValueError("expected 1 <= min_len <= max_len")

    programs: list[tuple[int, ...]] = []

    def rec(prefix: tuple[int, ...], target_len: int) -> None:
        if len(prefix) == target_len:
            programs.append(prefix)
            return
        for action in range(num_actions):
            rec(prefix + (action,), target_len)

    for length in range(min_len, max_len + 1):
        rec((), length)
    return programs


def split_programs(
    *,
    min_len: int = 1,
    max_len: int = 3,
    alpha: float = 1.0,
) -> tuple[list[tuple[int, ...]], list[tuple[int, ...]]]:
    """Create deterministic train and compositional-OOD program pools.

    `alpha` controls the fraction of short programs exposed during training.
    The remaining short programs become a compositional-OOD pool. This is an
    implementation assumption for the first reproduction pass.
    """

    if not 0.0 < alpha <= 1.0:
        raise ValueError("alpha must be in (0, 1]")

    programs = enumerate_programs(min_len=min_len, max_len=max_len)
    train_count = max(1, int(round(len(programs) * alpha)))
    return programs[:train_count], programs[train_count:]


def sample_state(rng: random.Random, *, size: int = 10) -> GridState:
    return GridState(row=rng.randrange(size), col=rng.randrange(size))


def sample_example(
    rng: random.Random,
    programs: Sequence[tuple[int, ...]],
    *,
    size: int = 10,
    boundary: BoundaryMode = "wrap",
) -> GridExample:
    if not programs:
        raise ValueError("program pool is empty")

    program = rng.choice(programs)
    support_x = sample_state(rng, size=size)
    query_x = sample_state(rng, size=size)
    support_y = apply_program(support_x, program, size=size, boundary=boundary)
    query_y = apply_program(query_x, program, size=size, boundary=boundary)

    return GridExample(
        support_x=support_x.to_index(size),
        support_y=support_y.to_index(size),
        query_x=query_x.to_index(size),
        query_y=query_y.to_index(size),
        program=program,
    )


def generate_examples(
    *,
    n: int,
    split: Literal["train", "id", "comp_ood", "length_ood"],
    seed: int,
    alpha: float = 1.0,
    size: int = 10,
    train_min_len: int = 1,
    train_max_len: int = 3,
    length_ood_min_len: int = 4,
    length_ood_max_len: int = 8,
    boundary: BoundaryMode = "wrap",
) -> list[GridExample]:
    """Generate a deterministic dataset split."""

    rng = random.Random(seed)
    train_programs, comp_programs = split_programs(
        min_len=train_min_len,
        max_len=train_max_len,
        alpha=alpha,
    )

    if split in {"train", "id"}:
        pool = train_programs
    elif split == "comp_ood":
        pool = comp_programs or train_programs
    elif split == "length_ood":
        pool = enumerate_programs(min_len=length_ood_min_len, max_len=length_ood_max_len)
    else:
        raise ValueError(f"unknown split: {split}")

    return [
        sample_example(rng, pool, size=size, boundary=boundary)
        for _ in range(n)
    ]


def iter_batches(items: Sequence[GridExample], batch_size: int) -> Iterator[list[GridExample]]:
    if batch_size <= 0:
        raise ValueError("batch_size must be positive")
    for start in range(0, len(items), batch_size):
        yield list(items[start : start + batch_size])

