"""GridWorld OTIB-style data generation.

The implementation keeps the domain deliberately small and auditable: a state is
one object on a 10x10 grid, and a hidden program is a sequence of primitive
moves. Each example contains a support transition and a query transition
generated by the same program.
"""

from __future__ import annotations

from dataclasses import dataclass
import random
from typing import Iterable, Iterator, Literal, Sequence

BoundaryMode = Literal["wrap", "clamp"]
SplitMode = Literal["random", "paper"]

ACTIONS: tuple[str, ...] = ("up", "down", "left", "right")
ACTION_TO_DELTA: dict[str, tuple[int, int]] = {
    "up": (-1, 0),
    "down": (1, 0),
    "left": (0, -1),
    "right": (0, 1),
}
PAPER_TOKEN_TO_ACTION: dict[str, str] = {
    "U": "up",
    "D": "down",
    "L": "left",
    "R": "right",
}


def parse_program(spec: str) -> tuple[int, ...]:
    return tuple(ACTIONS.index(PAPER_TOKEN_TO_ACTION[token]) for token in spec)


PAPER_GRIDWORLD_SPLITS: dict[float, tuple[tuple[str, ...], tuple[str, ...]]] = {
    0.33: (
        ("UUU", "DDD", "LLL", "RRR", "U", "LU", "DL", "DR", "DD", "DDL", "DRR"),
        ("L", "R", "D", "LL", "RR", "UU", "RU", "RRL", "LLU", "DLL", "RUU", "DDR", "RRU"),
    ),
    0.66: (
        (
            "UUU",
            "DDD",
            "LLL",
            "RRR",
            "U",
            "D",
            "R",
            "LU",
            "DL",
            "DR",
            "UU",
            "DD",
            "RR",
            "LUU",
            "LLU",
            "DRR",
            "DDR",
            "RRU",
        ),
        ("L", "LL", "DLL", "RU", "RUU", "DDR"),
    ),
}


@dataclass(frozen=True)
class GridState:
    row: int
    col: int

    def to_index(self, size: int = 10) -> int:
        return self.row * size + self.col

    @classmethod
    def from_index(cls, index: int, size: int = 10) -> "GridState":
        if index < 0 or index >= size * size:
            raise ValueError(f"state index {index} is outside a {size}x{size} grid")
        return cls(row=index // size, col=index % size)


@dataclass(frozen=True)
class GridExample:
    support_x: int
    support_y: int
    query_x: int
    query_y: int
    program: tuple[int, ...]


def apply_action(
    state: GridState,
    action: int | str,
    *,
    size: int = 10,
    boundary: BoundaryMode = "wrap",
) -> GridState:
    """Apply one primitive action to a state."""

    name = ACTIONS[action] if isinstance(action, int) else action
    if name not in ACTION_TO_DELTA:
        raise ValueError(f"unknown action: {action}")

    d_row, d_col = ACTION_TO_DELTA[name]
    row = state.row + d_row
    col = state.col + d_col

    if boundary == "wrap":
        row %= size
        col %= size
    elif boundary == "clamp":
        row = min(max(row, 0), size - 1)
        col = min(max(col, 0), size - 1)
    else:
        raise ValueError(f"unknown boundary mode: {boundary}")

    return GridState(row=row, col=col)


def apply_program(
    state: GridState,
    program: Sequence[int],
    *,
    size: int = 10,
    boundary: BoundaryMode = "wrap",
) -> GridState:
    """Apply a sequence of primitive actions."""

    current = state
    for action in program:
        current = apply_action(current, action, size=size, boundary=boundary)
    return current


def enumerate_programs(
    *,
    min_len: int = 1,
    max_len: int = 3,
    num_actions: int = len(ACTIONS),
) -> list[tuple[int, ...]]:
    """Enumerate all action programs in lexicographic order."""

    if min_len < 1 or max_len < min_len:
        raise ValueError("expected 1 <= min_len <= max_len")

    programs: list[tuple[int, ...]] = []

    def rec(prefix: tuple[int, ...], target_len: int) -> None:
        if len(prefix) == target_len:
            programs.append(prefix)
            return
        for action in range(num_actions):
            rec(prefix + (action,), target_len)

    for length in range(min_len, max_len + 1):
        rec((), length)
    return programs


def split_programs(
    *,
    min_len: int = 1,
    max_len: int = 3,
    alpha: float = 1.0,
    seed: int = 0,
    use_anchors: bool = True,
    split_mode: SplitMode = "random",
    paper_singleton: str = "U",
) -> tuple[list[tuple[int, ...]], list[tuple[int, ...]]]:
    """Create deterministic train and compositional-OOD program pools.

    `alpha` controls the fraction of short programs exposed during training.
    For the paper-aligned GridWorld split, the four triple-move anchor programs
    are always included, and alpha is applied to the remaining short programs.
    """

    if not 0.0 < alpha <= 1.0:
        raise ValueError("alpha must be in (0, 1]")

    if split_mode == "paper":
        if min_len != 1 or max_len != 3:
            raise ValueError("paper split is defined for GridWorld short programs of length 1-3")
        if not use_anchors:
            raise ValueError("paper split requires anchors")
        if alpha == 1.0:
            return enumerate_programs(min_len=min_len, max_len=max_len), []
        for paper_alpha, (train_specs, comp_specs) in PAPER_GRIDWORLD_SPLITS.items():
            if abs(alpha - paper_alpha) < 1e-9:
                if paper_alpha == 0.33 and paper_singleton not in {"U", "L", "ALL"}:
                    raise ValueError("paper_singleton must be U, L, or ALL")
                if paper_alpha == 0.33 and paper_singleton == "L":
                    train_specs = tuple("L" if spec == "U" else spec for spec in train_specs)
                    comp_specs = tuple("U" if spec == "L" else spec for spec in comp_specs)
                elif paper_alpha == 0.33 and paper_singleton == "ALL":
                    train_specs = tuple(
                        list(train_specs[:4])
                        + ["U", "D", "L", "R"]
                        + list(train_specs[5:])
                    )
                    comp_specs = tuple(spec for spec in comp_specs if len(spec) != 1)
                return [parse_program(spec) for spec in train_specs], [parse_program(spec) for spec in comp_specs]
        raise ValueError("paper split is defined only for alpha 0.33, 0.66, and 1.0")
    if split_mode != "random":
        raise ValueError(f"unknown split_mode: {split_mode}")

    programs = enumerate_programs(min_len=min_len, max_len=max_len)
    if not use_anchors:
        train_count = max(1, int(round(len(programs) * alpha)))
        return programs[:train_count], programs[train_count:]

    anchors = [
        (action, action, action)
        for action in range(len(ACTIONS))
        if min_len <= 3 <= max_len
    ]
    anchor_set = set(anchors)
    remaining = [program for program in programs if program not in anchor_set]
    rng = random.Random(seed)
    shuffled = list(remaining)
    rng.shuffle(shuffled)
    train_count = int(round(len(shuffled) * alpha))
    train_count = min(len(shuffled), max(0, train_count))
    train_programs = anchors + sorted(shuffled[:train_count])
    comp_programs = sorted(shuffled[train_count:])
    if not train_programs:
        train_programs = [programs[0]]
        comp_programs = programs[1:]
    return train_programs, comp_programs


def sample_state(rng: random.Random, *, size: int = 10) -> GridState:
    return GridState(row=rng.randrange(size), col=rng.randrange(size))


def sample_example(
    rng: random.Random,
    programs: Sequence[tuple[int, ...]],
    *,
    size: int = 10,
    boundary: BoundaryMode = "wrap",
) -> GridExample:
    if not programs:
        raise ValueError("program pool is empty")

    program = rng.choice(programs)
    support_x = sample_state(rng, size=size)
    query_x = sample_state(rng, size=size)
    support_y = apply_program(support_x, program, size=size, boundary=boundary)
    query_y = apply_program(query_x, program, size=size, boundary=boundary)

    return GridExample(
        support_x=support_x.to_index(size),
        support_y=support_y.to_index(size),
        query_x=query_x.to_index(size),
        query_y=query_y.to_index(size),
        program=program,
    )


def generate_examples(
    *,
    n: int,
    split: Literal["train", "id", "comp_ood", "length_ood"],
    seed: int,
    alpha: float = 1.0,
    size: int = 10,
    train_min_len: int = 1,
    train_max_len: int = 3,
    length_ood_min_len: int = 4,
    length_ood_max_len: int = 8,
    split_seed: int = 0,
    use_anchors: bool = True,
    boundary: BoundaryMode = "wrap",
    split_mode: SplitMode = "random",
    paper_singleton: str = "U",
) -> list[GridExample]:
    """Generate a deterministic dataset split."""

    rng = random.Random(seed)
    train_programs, comp_programs = split_programs(
        min_len=train_min_len,
        max_len=train_max_len,
        alpha=alpha,
        seed=split_seed,
        use_anchors=use_anchors,
        split_mode=split_mode,
        paper_singleton=paper_singleton,
    )

    if split in {"train", "id"}:
        pool = train_programs
    elif split == "comp_ood":
        pool = comp_programs or train_programs
    elif split == "length_ood":
        pool = enumerate_programs(min_len=length_ood_min_len, max_len=length_ood_max_len)
    else:
        raise ValueError(f"unknown split: {split}")

    return [
        sample_example(rng, pool, size=size, boundary=boundary)
        for _ in range(n)
    ]


def iter_batches(items: Sequence[GridExample], batch_size: int) -> Iterator[list[GridExample]]:
    if batch_size <= 0:
        raise ValueError("batch_size must be positive")
    for start in range(0, len(items), batch_size):
        yield list(items[start : start + batch_size])
